name: flutter_aws_s3_client
description: A simple, unofficial AWS S3 client in dart. Supports downloading objects and listing objects in a bucket.
version: 0.5.2
author: Diagnosia <support@diagnosia.com>
homepage: https://github.com/diagnosia/flutter_aws_s3_client
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^0.1.14
  built_value: ">=6.8.0 <8.0.0"
  built_collection: ">=4.0.0 <5.0.0"
  xml2json : ^4.2.0
  http: ^0.12.1
dev_dependencies:
  built_value_generator: ">=6.8.0 <8.0.0"
  build_runner: ^1.10.0
  json_serializable: ">=3.2.2 <4.0.0"

